/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as QrTokenRouteImport } from './routes/qr/$token'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as AttendanceMarkedRouteImport } from './routes/attendance/marked'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardStatusesIndexRouteImport } from './routes/dashboard/statuses/index'
import { Route as DashboardSessionsIndexRouteImport } from './routes/dashboard/sessions/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardUsersImportDocumentRouteImport } from './routes/dashboard/users/import-document'
import { Route as DashboardUsersBulkUploadRouteImport } from './routes/dashboard/users/bulk-upload'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardSessionsCreateRouteImport } from './routes/dashboard/sessions/create'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions/$sessionId'
import { Route as DashboardReportsBatteriesRouteImport } from './routes/dashboard/reports/batteries'
import { Route as DashboardAttendanceScanRouteImport } from './routes/dashboard/attendance/scan'
import { Route as DashboardAdminRegistrationsIndexRouteImport } from './routes/dashboard/admin/registrations/index'
import { Route as DashboardReportsSessionsSessionIdRouteImport } from './routes/dashboard/reports/sessions/$sessionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTokenRoute = QrTokenRouteImport.update({
  id: '/qr/$token',
  path: '/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceMarkedRoute = AttendanceMarkedRouteImport.update({
  id: '/attendance/marked',
  path: '/attendance/marked',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/dashboard/users/',
  path: '/dashboard/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStatusesIndexRoute = DashboardStatusesIndexRouteImport.update({
  id: '/dashboard/statuses/',
  path: '/dashboard/statuses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({
  id: '/dashboard/sessions/',
  path: '/dashboard/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/dashboard/reports/',
  path: '/dashboard/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersImportDocumentRoute =
  DashboardUsersImportDocumentRouteImport.update({
    id: '/dashboard/users/import-document',
    path: '/dashboard/users/import-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUsersBulkUploadRoute =
  DashboardUsersBulkUploadRouteImport.update({
    id: '/dashboard/users/bulk-upload',
    path: '/dashboard/users/bulk-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/dashboard/users/$userId',
  path: '/dashboard/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSessionsCreateRoute = DashboardSessionsCreateRouteImport.update({
  id: '/dashboard/sessions/create',
  path: '/dashboard/sessions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/dashboard/sessions/$sessionId',
    path: '/dashboard/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardReportsBatteriesRoute =
  DashboardReportsBatteriesRouteImport.update({
    id: '/dashboard/reports/batteries',
    path: '/dashboard/reports/batteries',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAttendanceScanRoute = DashboardAttendanceScanRouteImport.update({
  id: '/dashboard/attendance/scan',
  path: '/dashboard/attendance/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRegistrationsIndexRoute =
  DashboardAdminRegistrationsIndexRouteImport.update({
    id: '/dashboard/admin/registrations/',
    path: '/dashboard/admin/registrations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardReportsSessionsSessionIdRoute =
  DashboardReportsSessionsSessionIdRouteImport.update({
    id: '/dashboard/reports/sessions/$sessionId',
    path: '/dashboard/reports/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/attendance/marked': typeof AttendanceMarkedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/qr/$token': typeof QrTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/attendance/scan': typeof DashboardAttendanceScanRoute
  '/dashboard/reports/batteries': typeof DashboardReportsBatteriesRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/sessions/create': typeof DashboardSessionsCreateRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/users/bulk-upload': typeof DashboardUsersBulkUploadRoute
  '/dashboard/users/import-document': typeof DashboardUsersImportDocumentRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/sessions': typeof DashboardSessionsIndexRoute
  '/dashboard/statuses': typeof DashboardStatusesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/reports/sessions/$sessionId': typeof DashboardReportsSessionsSessionIdRoute
  '/dashboard/admin/registrations': typeof DashboardAdminRegistrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/attendance/marked': typeof AttendanceMarkedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/qr/$token': typeof QrTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/attendance/scan': typeof DashboardAttendanceScanRoute
  '/dashboard/reports/batteries': typeof DashboardReportsBatteriesRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/sessions/create': typeof DashboardSessionsCreateRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/users/bulk-upload': typeof DashboardUsersBulkUploadRoute
  '/dashboard/users/import-document': typeof DashboardUsersImportDocumentRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/sessions': typeof DashboardSessionsIndexRoute
  '/dashboard/statuses': typeof DashboardStatusesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/reports/sessions/$sessionId': typeof DashboardReportsSessionsSessionIdRoute
  '/dashboard/admin/registrations': typeof DashboardAdminRegistrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/attendance/marked': typeof AttendanceMarkedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/qr/$token': typeof QrTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/attendance/scan': typeof DashboardAttendanceScanRoute
  '/dashboard/reports/batteries': typeof DashboardReportsBatteriesRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/sessions/create': typeof DashboardSessionsCreateRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/users/bulk-upload': typeof DashboardUsersBulkUploadRoute
  '/dashboard/users/import-document': typeof DashboardUsersImportDocumentRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/dashboard/statuses/': typeof DashboardStatusesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/reports/sessions/$sessionId': typeof DashboardReportsSessionsSessionIdRoute
  '/dashboard/admin/registrations/': typeof DashboardAdminRegistrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/attendance/marked'
    | '/dashboard/settings'
    | '/qr/$token'
    | '/dashboard'
    | '/dashboard/attendance/scan'
    | '/dashboard/reports/batteries'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/sessions/create'
    | '/dashboard/users/$userId'
    | '/dashboard/users/bulk-upload'
    | '/dashboard/users/import-document'
    | '/dashboard/reports'
    | '/dashboard/sessions'
    | '/dashboard/statuses'
    | '/dashboard/users'
    | '/dashboard/reports/sessions/$sessionId'
    | '/dashboard/admin/registrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/attendance/marked'
    | '/dashboard/settings'
    | '/qr/$token'
    | '/dashboard'
    | '/dashboard/attendance/scan'
    | '/dashboard/reports/batteries'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/sessions/create'
    | '/dashboard/users/$userId'
    | '/dashboard/users/bulk-upload'
    | '/dashboard/users/import-document'
    | '/dashboard/reports'
    | '/dashboard/sessions'
    | '/dashboard/statuses'
    | '/dashboard/users'
    | '/dashboard/reports/sessions/$sessionId'
    | '/dashboard/admin/registrations'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/attendance/marked'
    | '/dashboard/settings'
    | '/qr/$token'
    | '/dashboard/'
    | '/dashboard/attendance/scan'
    | '/dashboard/reports/batteries'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/sessions/create'
    | '/dashboard/users/$userId'
    | '/dashboard/users/bulk-upload'
    | '/dashboard/users/import-document'
    | '/dashboard/reports/'
    | '/dashboard/sessions/'
    | '/dashboard/statuses/'
    | '/dashboard/users/'
    | '/dashboard/reports/sessions/$sessionId'
    | '/dashboard/admin/registrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  AttendanceMarkedRoute: typeof AttendanceMarkedRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  QrTokenRoute: typeof QrTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAttendanceScanRoute: typeof DashboardAttendanceScanRoute
  DashboardReportsBatteriesRoute: typeof DashboardReportsBatteriesRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardSessionsCreateRoute: typeof DashboardSessionsCreateRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardUsersBulkUploadRoute: typeof DashboardUsersBulkUploadRoute
  DashboardUsersImportDocumentRoute: typeof DashboardUsersImportDocumentRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
  DashboardStatusesIndexRoute: typeof DashboardStatusesIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardReportsSessionsSessionIdRoute: typeof DashboardReportsSessionsSessionIdRoute
  DashboardAdminRegistrationsIndexRoute: typeof DashboardAdminRegistrationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$token': {
      id: '/qr/$token'
      path: '/qr/$token'
      fullPath: '/qr/$token'
      preLoaderRoute: typeof QrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/marked': {
      id: '/attendance/marked'
      path: '/attendance/marked'
      fullPath: '/attendance/marked'
      preLoaderRoute: typeof AttendanceMarkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/statuses/': {
      id: '/dashboard/statuses/'
      path: '/dashboard/statuses'
      fullPath: '/dashboard/statuses'
      preLoaderRoute: typeof DashboardStatusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sessions/': {
      id: '/dashboard/sessions/'
      path: '/dashboard/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/import-document': {
      id: '/dashboard/users/import-document'
      path: '/dashboard/users/import-document'
      fullPath: '/dashboard/users/import-document'
      preLoaderRoute: typeof DashboardUsersImportDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/bulk-upload': {
      id: '/dashboard/users/bulk-upload'
      path: '/dashboard/users/bulk-upload'
      fullPath: '/dashboard/users/bulk-upload'
      preLoaderRoute: typeof DashboardUsersBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/dashboard/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sessions/create': {
      id: '/dashboard/sessions/create'
      path: '/dashboard/sessions/create'
      fullPath: '/dashboard/sessions/create'
      preLoaderRoute: typeof DashboardSessionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sessions/$sessionId': {
      id: '/dashboard/sessions/$sessionId'
      path: '/dashboard/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/batteries': {
      id: '/dashboard/reports/batteries'
      path: '/dashboard/reports/batteries'
      fullPath: '/dashboard/reports/batteries'
      preLoaderRoute: typeof DashboardReportsBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/attendance/scan': {
      id: '/dashboard/attendance/scan'
      path: '/dashboard/attendance/scan'
      fullPath: '/dashboard/attendance/scan'
      preLoaderRoute: typeof DashboardAttendanceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/registrations/': {
      id: '/dashboard/admin/registrations/'
      path: '/dashboard/admin/registrations'
      fullPath: '/dashboard/admin/registrations'
      preLoaderRoute: typeof DashboardAdminRegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/sessions/$sessionId': {
      id: '/dashboard/reports/sessions/$sessionId'
      path: '/dashboard/reports/sessions/$sessionId'
      fullPath: '/dashboard/reports/sessions/$sessionId'
      preLoaderRoute: typeof DashboardReportsSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  AttendanceMarkedRoute: AttendanceMarkedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  QrTokenRoute: QrTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAttendanceScanRoute: DashboardAttendanceScanRoute,
  DashboardReportsBatteriesRoute: DashboardReportsBatteriesRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
  DashboardSessionsCreateRoute: DashboardSessionsCreateRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardUsersBulkUploadRoute: DashboardUsersBulkUploadRoute,
  DashboardUsersImportDocumentRoute: DashboardUsersImportDocumentRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardSessionsIndexRoute: DashboardSessionsIndexRoute,
  DashboardStatusesIndexRoute: DashboardStatusesIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardReportsSessionsSessionIdRoute:
    DashboardReportsSessionsSessionIdRoute,
  DashboardAdminRegistrationsIndexRoute: DashboardAdminRegistrationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
